
name: test

on:
  push:
  schedule:
    - cron: '* * * * *'



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: Shanghai Weather Report
          body: file://result.html
          to: 364271511@qq.com
          from: GitHub Actions
          content_type: text/html
